### ISSUE TITLE
Create a Readme.md file for this repo

### ISSUE THREAD

**Issue by SakshamAgrwl** [SakshamAgrwl/GFG-DSA-Problem-Solutions#16]
Create a good readme.md file for this repo.
<ul>
   <li> The readme should be more informative so that a new user can easily browse through all the problems </li>
   <li> Make sure you add hacktoberfest as label for this repo so that the Pr's are accepted for hacktoberfest </li>
   <li> You can take some examples from https://github.com/vinitshahdeo/HBD.git this repo</li>
   <li> Don't take this issue just for that 👕 . Think of it as it is your own repository.</li>

**Comment by SakshamAgrwl** [comment]
@Samridhi-98  Please work on this issue, otherwise the PR will not be considered for hacktoberfest

**Comment by Kartik987** [comment]
Added palindromic string and Fibonacci series. please check.
