### ISSUE TITLE
Add Rabin Karp Algorithm

### ISSUE THREAD

**Issue by SakshamAgrwl** [SakshamAgrwl/GFG-DSA-Problem-Solutions#3]
Add Rabin Karp algorithm code in C++. Please upload the code in strings folder and the directory structure should be strings/rabin_karp.cpp

**Comment by sabazubair** [comment]
Hey Saksham, I am learning C++ and I would like to take this on! It will be challenging but I think I will learn a lot. Thanks for sharing this opportunity.

**Comment by vibalijoshi** [comment]
I added the Rabin Karp algorithm code in C++ in the strings folder, and made a PR request, please check

**Comment by SakshamAgrwl** [comment]
Great work @vibalijoshi . Your PR is merged now.

**Comment by saks1209am** [comment]
@sabazubair You can work on other issues. New issues have been added, please go ahead and work on them😊

**Comment by vibalijoshi** [comment]
> Great work @vibalijoshi . Your PR is merged now.

Thanks for this opportunity! I was wondering why my Hacktoberfest account is still showing zero pull requests!

**Comment by saks1209am** [comment]
@vibalijoshi Please look to issue #16 . Make sure you create a readme with mentioned guidelines which u can find in this issue. Complete the issue so that ur PR's are accepted for hacktoberfest.

**Comment by saks1209am** [comment]
@sabazubair You can work on #16  this issue.
