### ISSUE TITLE
Add Pattern question solutions

### ISSUE THREAD

**Issue by SakshamAgrwl** [SakshamAgrwl/GFG-DSA-Problem-Solutions#9]
<ol>
  <b>
   <li> Create a new folder named Patterns</li>
   <li> Add pattern problem solutions in that folder </li>
   <li> Comment on the issue </li>
   <li> Open a PR </li>
   <li> 🌟this repo </li> 
   </b>
</ol>

**Comment by yrahul3910** [comment]
On it!

**Comment by yrahul3910** [comment]
Do you mean pattern-printing or pattern search? And how many problems?

**Comment by Manoj13-coder** [comment]
i am interested in it assign it to me

**Comment by SakshamAgrwl** [comment]
Sorry, my mistake. Pattern questions are not there in DS and Algo. I will be creating a new issue for that. @yrahul3910 @Manoj13-coder please have a look on the new issues .

**Comment by Manoj13-coder** [comment]
ok no problem
